# Sklearn

## sklearn.cross_validation

документация: http://scikit-learn.org/stable/modules/cross_validation.html

In [3]:
from sklearn import cross_validation, datasets

import numpy as np

### Разовое разбиение данных на обучение и тест с помощью train_test_split

In [4]:
iris = datasets.load_iris()

In [5]:
type(iris.data)

numpy.ndarray

In [27]:
train_data, test_data, train_labels, test_labels = cross_validation.train_test_split(iris.data, iris.target, 
                                                                                     test_size = 0.3)

In [28]:
test_labels

array([1, 2, 1, 0, 0, 0, 1, 0, 2, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 2, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 2, 0, 1, 2, 1, 2, 2, 0, 0, 0, 2, 2, 0, 2, 1])

In [29]:
#убедимся, что тестовая выборка действительно составляет 0.3 от всех данных
float(len(test_labels))/len(iris.data)

0.3

In [30]:
print 'Размер обучающей выборки: {} объектов \nРазмер тестовой выборки: {} объектов'.format(len(train_data),
                                                                                            len(test_data))

Размер обучающей выборки: 105 объектов 
Размер тестовой выборки: 45 объектов


In [31]:
print 'Обучающая выборка:\n', train_data[:5]
print '\n'
print 'Тестовая выборка:\n', test_data[:5]

Обучающая выборка:
[[ 7.7  2.8  6.7  2. ]
 [ 5.5  2.4  3.7  1. ]
 [ 5.7  4.4  1.5  0.4]
 [ 6.   3.   4.8  1.8]
 [ 6.4  2.9  4.3  1.3]]


Тестовая выборка:
[[ 6.8  2.8  4.8  1.4]
 [ 6.9  3.2  5.7  2.3]
 [ 6.   3.4  4.5  1.6]
 [ 4.6  3.1  1.5  0.2]
 [ 5.2  3.5  1.5  0.2]]


In [32]:
print 'Метки классов на обучающей выборке:\n', train_labels
print '\n'
print 'Метки классов на тестовой выборке:\n', test_labels

Метки классов на обучающей выборке:
[2 1 0 2 1 2 0 0 1 2 1 2 1 1 0 2 0 0 2 2 2 2 2 0 1 2 2 0 0 0 0 1 2 2 1 0 1
 0 2 0 1 0 2 2 1 2 1 1 2 2 1 2 2 2 0 2 0 1 1 0 1 0 0 0 0 2 2 1 1 1 0 2 1 1
 0 1 1 2 0 2 1 1 0 1 2 2 2 2 1 1 2 2 1 1 0 2 2 0 1 0 0 2 1 2 1]


Метки классов на тестовой выборке:
[1 2 1 0 0 0 1 0 2 1 0 1 0 1 1 1 1 0 1 0 2 0 0 1 0 0 1 0 0 0 2 0 1 2 1 2 2
 0 0 0 2 2 0 2 1]


### Стратегии проведения кросс-валидации

#### KFold

In [33]:
for train_indices, test_indices in cross_validation.KFold(10, n_folds = 5):
    print train_indices, test_indices

[2 3 4 5 6 7 8 9] [0 1]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]


In [35]:
for train_indices, test_indices in cross_validation.KFold(10, n_folds = 2, shuffle = True):
    print train_indices, test_indices

[0 1 2 5 7] [3 4 6 8 9]
[3 4 6 8 9] [0 1 2 5 7]


In [38]:
for train_indices, test_indices in cross_validation.KFold(10, n_folds = 2, shuffle = True, random_state = 1):
    print train_indices, test_indices

[1 3 5 7 8] [0 2 4 6 9]
[0 2 4 6 9] [1 3 5 7 8]


#### StratifiedKFold

In [39]:
target = np.array([0] * 5 + [1] * 5)
print target
for train_indices, test_indices in cross_validation.StratifiedKFold(target, n_folds = 2, shuffle = True, random_state = 0):
    print train_indices, test_indices

[0 0 0 0 0 1 1 1 1 1]
[3 4 8 9] [0 1 2 5 6 7]
[0 1 2 5 6 7] [3 4 8 9]


In [40]:
target = np.array([0, 1] * 5)
print target
for train_indices, test_indices in cross_validation.StratifiedKFold(target, n_folds = 2,shuffle = True):
    print train_indices, test_indices

[0 1 0 1 0 1 0 1 0 1]
[0 3 4 5] [1 2 6 7 8 9]
[1 2 6 7 8 9] [0 3 4 5]


#### ShuffleSplit

In [24]:
for train_indices, test_indices in cross_validation.ShuffleSplit(10, n_iter = 10, test_size = 0.2):
    print train_indices, test_indices

[9 4 6 1 8 7 2 5] [0 3]
[4 7 5 8 1 2 0 6] [9 3]
[9 2 6 4 8 5 1 7] [3 0]
[7 3 8 2 0 6 4 1] [5 9]
[6 8 2 3 1 7 9 0] [5 4]
[7 5 3 6 4 0 9 1] [2 8]
[3 9 2 1 5 4 7 0] [6 8]
[9 3 2 4 0 8 6 5] [7 1]
[2 1 0 6 9 4 8 3] [5 7]
[9 1 6 0 4 8 7 2] [5 3]


#### StratifiedShuffleSplit

In [25]:
target = np.array([0] * 5 + [1] * 5)
print target
for train_indices, test_indices in cross_validation.StratifiedShuffleSplit(target, n_iter = 4, test_size = 0.2):
    print train_indices, test_indices

[0 0 0 0 0 1 1 1 1 1]
[2 9 7 4 3 0 5 6] [8 1]
[8 3 0 4 6 9 2 7] [5 1]
[8 6 5 0 7 2 3 4] [9 1]
[8 3 4 5 2 1 7 6] [9 0]


#### Leave-One-Out

In [41]:
for train_indices, test_index in cross_validation.LeaveOneOut(10):
    print train_indices, test_index

[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]


Больше стратегий проведения кросс-валидации доступно здесь: http://scikit-learn.org/stable/modules/cross_validation.html#cross-validation-iterators